### PR TITLE
Fixing update method in rack resource

### LINKED ISSUE #226: Add_rack_resource method returns NOMATCHING_ETAG_MESSAGE
### Scenario/Intent
Run the `OneviewSDK::Rack`'s method `add_rack_resource` to add a new resource to the rack.

### Environment Details
 - **OneView Appliance Version:** 300/C7000

### Steps to Reproduce
I've used the example and added the add_rack_resource method expecting it to work, but got issues.
Follows the updated example:
```ruby
item = OneviewSDK::API300::C7000::Rack.new(@client, options)
item.add
puts "Rack #{item['name']} was added with uri='#{item['uri']}'"

enc = OneviewSDK::API300::C7000::Enclosure.find_by(@client, {}).first
item.add_rack_resource(enc)
item.update #fails at this point with the NOMATCHING_ETAG_MESSAGE message
puts "Rack #{item['name']} was updated with new enclosure '#{enc['name']}'" ## We don't really get here
```

### Expected Result
The enclosure would've been added to the rack

### Actual Result
NOMATCHING_ETAG_MESSAGE raised

### PR DESCRIPTION
**Pull request by aalexmonteiro**
### Description
Fixing update method in rack resource

### Issues Resolved
#226 

### Check List
- [ ] New functionality includes testing.
  - [x] All tests pass (`$ rake test`).
- [ ] New functionality has been documented in the README if applicable.
  - [ ] New functionality has been thoroughly documented in the examples (please include helpful comments).
- [ ] New endpoints supported are updated in the endpoints-support.md file.
- [x] Changes are documented in the CHANGELOG.

### CODE REVIEW

File: lib/oneview-sdk/resource/api200/rack.rb [hunk 1]
```diff
@@ -51,6 +51,13 @@ def delete(*)
         unavailable_method
       end
 
+      # Updates a rack
+      # @param [Hash] attributes attributes to be updated
+      # @return [OneviewSDK::Rack] self
+      def update(attributes = {}, header = self.class::DEFAULT_REQUEST_HEADER)
```
Comment (fgbulsoni) [inline lib/oneview-sdk/resource/api200/rack.rb]: Question: What exactly are does `self.class::DEFAULT_REQUEST_HEADER` resolves to? `{}.freeze`?
Can't we just `header  = { 'If-Match' => '*' }` here?

Comment (aalexmonteiro) [reply lib/oneview-sdk/resource/api200/rack.rb]: Really! Good catch.
