### PR TITLE
Logical Interconnect API300 Support

### LINKED ISSUE #103: Logical Interconnect API 300 Support
### Scenario/Intent
Use the Logical Interconnect resource for API 300 C7000/Synergy

### Environment Details
 - **OneView SDK Version: Future
 - **OneView Appliance Version: 300
 - **OneView Client API Version: 300
 - **Ruby Version: 2.2.3+
 - **Platform: w/e

### Steps to Reproduce
Trying to run the resource with the OneviewSDK::API300:::: syntax

### Expected Result
Being able to call the resource methods and use it.

### Actual Result
It's currently not implemented, resulting in method unavailable.

### PR DESCRIPTION
**Pull request by aalexmonteiro**
### Description
Implementation of the logical interconnect for API300 support.

### Issues Resolved
#103 

### Check List
- [x] New functionality includes testing.
  - [x] All tests pass (`$ rake test`).
- [ ] New functionality has been documented in the README if applicable.
  - [x] New functionality has been thoroughly documented in the examples (please include helpful comments).
- [x] Changes are documented in the CHANGELOG.

### CODE REVIEW

**Comment by aalexmonteiro** [comment]
To perform the Logical Interconnect tests, it was necessary to change some tests, such as enclosure-group, logical-interconnect-group and logical-enclosure.

File: lib/oneview-sdk/resource/api300/synergy/logical_interconnect.rb [hunk 1]
```diff
@@ -9,12 +9,33 @@
...
 module OneviewSDK
   module API300
     module Synergy
-      class LogicalInterconnect < OneviewSDK::API200::LogicalInterconnect
+      # Logical interconnect resource implementation for API300 Synergy
+      class LogicalInterconnect < OneviewSDK::API300::C7000::LogicalInterconnect
+
+        # Lists internal networks on the logical interconnect
+        # @return [OneviewSDK::Resource] List of networks
+        def list_vlan_networks
```
Comment (fgbulsoni) [inline lib/oneview-sdk/resource/api300/synergy/logical_interconnect.rb]: Why add this method to both the c7000 and synergy files, if the synergy is inheriting it from the c7000?
If the other methods from the c7000 api 300 should not be inherited, this resource should inherit directly from api 200. If they should be inherited and that is expected, this method does not need to be duplicated here.

Comment (fgbulsoni) [inline lib/oneview-sdk/resource/api300/synergy/logical_interconnect.rb]: Ok, nvm. I'm guessing its due the 'net' assignment which uses Synergy namespaces here instead of C7000.

Comment (aalexmonteiro) [inline lib/oneview-sdk/resource/api300/synergy/logical_interconnect.rb]: @fgbulsoni exactly. Because this method can return an EthernetNetwork or FCNetwork or FCoENetwork to its respective model (C7000 or Synergy).

Comment (aalexmonteiro) [inline lib/oneview-sdk/resource/api300/synergy/logical_interconnect.rb]: @fgbulsoni the inheritance LogicalInterconnect < OneviewSDK::API300::C7000::LogicalInterconnect was due to the update_settings method. This method is common to both.

Comment (fgbulsoni) [inline lib/oneview-sdk/resource/api300/synergy/logical_interconnect.rb]: That's fine. I'm hitting a few failing tests on my appliances, but it might be my conf. If all integrations for both C7000 and Synergy are passing there, just fix the ``CHANGELOG.md`` and it should be good to merge.

Comment (aalexmonteiro) [inline lib/oneview-sdk/resource/api300/synergy/logical_interconnect.rb]: @fgbulsoni I'm testing again. In Synergy, a few moments the tests fail, but I think due to the device and others moments the tests passed. I'm making sure of that now.

**Comment by aalexmonteiro** [comment]
@fgbulsoni I ran the tests. For C7000 executed successfully. For synergy executed successfully, but sometimes the test for update_settings failed. I think it's due to inconsistent device.

**Comment by fgbulsoni** [comment]
PR is facing conflicts post the merge of PR #110 , CHANGELOG.md should be reviewed to fix conflicts.

**Comment by aalexmonteiro** [comment]
@fgbulsoni Fixed merge conflicts.

File: CHANGELOG.md [hunk 2]
```diff
@@ -1,5 +1,6 @@
 # v3.1.0
  1. Added full support to OneView Rest API version 300 for the hardware variants C7000 and Synergy to the already existing features:
+   - Logical Interconnect
    - Uplink Set
 
 ### Features supported
```
Comment (fgbulsoni) [inline CHANGELOG.md]: Should also add the item bellow features supported

File: lib/oneview-sdk/resource/api200/logical_interconnect.rb [hunk 3]
```diff
@@ -133,6 +143,17 @@ def configuration
         set_all(body)
       end
 
+      # Gets a collection of uplink ports from the member interconnects
+      # which are eligible for assignment to an analyzer port.
+      # @return [Hash] Hash of uplink ports eligibles for assignment to an analyzer port
+      def get_unassigned_up_link_ports_for_port_monitor
```
Comment (fgbulsoni) [inline lib/oneview-sdk/resource/api200/logical_interconnect.rb]: Maybe uplink could be together instead of separated by _?

File: CHANGELOG.md (hunk 2 above)
Comment (aalexmonteiro) [inline CHANGELOG.md]: @fgbulsoni already added.

**Comment by aalexmonteiro** [comment]
@fgbulsoni review changes fixed.
