### PR TITLE
Bugfix in timeout Firmware Bundle

### LINKED ISSUE #135: Firmware Bundle timeout does not give proper instructions for user post failure
### Scenario/Intent
Have a clearer output when failing due to timeouts on firmware uploads

### Steps to Reproduce
Run firmware_bundle with a small timeout and upload a big image.

### Expected Result
It should fail and tell the user it closed the connection due to the timeout option that can be specified and changed, and it should also instruct the user on what to do next. i.e. if the firmware is left as corrupted on the oneview appliance, it should tell that to the user and instruct that it should be cleaned up. 

### Actual Result
Simply fails.

### PR DESCRIPTION
**Pull request by aalexmonteiro**
### Description
Have a clearer output when failing due to timeouts on firmware uploads.

### Issues Resolved
#135 

### Check List
- [x] New functionality includes testing.
  - [x] All tests pass (`$ rake test`).
- [ ] New functionality has been documented in the README if applicable.
  - [ ] New functionality has been thoroughly documented in the examples (please include helpful comments).
- [x] Changes are documented in the CHANGELOG.

### CODE REVIEW

File: lib/oneview-sdk/resource/api200/firmware_bundle.rb [hunk 1]
```diff
@@ -45,9 +45,15 @@ def self.add(client, file_path, timeout = READ_TIMEOUT)
...
-            data = client.response_handler(response)
-            return OneviewSDK::FirmwareDriver.new(client, data)
+            begin
+              response = http.request(req)
+              data = client.response_handler(response)
+              return OneviewSDK::FirmwareDriver.new(client, data)
+            rescue Net::ReadTimeout
+              raise "The connection was closed because the timeout of #{timeout} seconds has expired."\
+                'You can specify the timeout in seconds by passing the timeout on the method call.'\
+                'If the firmware is corrupted in the search appliance, you should clean it.'
```
Comment (fgbulsoni) [inline lib/oneview-sdk/resource/api200/firmware_bundle.rb]: For this line, I'd prefer something like:
'Interrupted firmware uploads may result in the corrupted firmware remaining in the appliance. HPE recommends checking the appliance for such corrupted firmware and removing it. '

**Comment by aalexmonteiro** [comment]
@fgbulsoni , done. Please check if this is good. :)
