### PR TITLE
Plan Scripts i3s API300 Support

### LINKED ISSUE #120: I3S - Plan Scripts API 300 Support
### Scenario/Intent
Use the Image Streamer - Plan Scripts resource for API 300 C7000/Synergy.

### Environment Details
 - **OneView SDK Version: Future
 - **OneView Appliance Version: 300
 - **OneView Client API Version: 300
 - **Ruby Version: 2.2.3+
 - **Platform: w/e

### Steps to Reproduce
Trying to run the resource of Image Streamer for API 300.

### Expected Result
Being able to call the resource methods and use it.

### Actual Result
It's currently not implemented.

### PR DESCRIPTION
**Pull request by aalexmonteiro**
### Description
Implementation of the plan script for i3s API300 support.

### Issues Resolved
#120 

### Check List
- [x] New functionality includes testing.
  - [x] All tests pass (`$ rake test`).
- [ ] New functionality has been documented in the README if applicable.
  - [x] New functionality has been thoroughly documented in the examples (please include helpful comments).
- [ ] Changes are documented in the CHANGELOG.

### CODE REVIEW

**Comment by aalexmonteiro** [comment]
This PR was implemented the plan scripts resource, as well as was created the structure for creating examples and tests of integrations.

To run integration tests for i3s, use <rake spec:integration:i3s>. Also specific tasks were created such as create, update, delete for i3s and specific i3s version.

Feel free to give criticisms and suggestions. :)

File: Rakefile [hunk 1]
```diff
@@ -26,6 +26,7 @@ RSpec::Core::RakeTask.new(:spec) do |spec|
   spec.rspec_opts = def_spec_options
   spec.rspec_opts << ' --tag ~integration'
   spec.rspec_opts << ' --tag ~system'
+  spec.rspec_opts << ' --tag ~integration_i3s'
```
Comment (tmiotto) [inline Rakefile]: It won't be better to use two tags, instead creating one tag for each specific combination?

File: examples/_client_i3s.rb.example [hunk 2]
```diff
@@ -0,0 +1,15 @@
+require_relative './../lib/oneview-sdk/image_streamer'
+require 'pry'
+
+# Client to the Image Streamer
```
Comment (tmiotto) [inline examples/_client_i3s.rb.example]: "Client for HPE Image Streamer"

File: examples/_client_i3s.rb.example [hunk 3]
```diff
@@ -0,0 +1,15 @@
...
+@client = OneviewSDK::ImageStreamer::Client.new(
+  url: 'https://oneview.example.com', # or set ENV['ONEVIEWSDK_I3S_URL']
```
Comment (tmiotto) [inline examples/_client_i3s.rb.example]: OneView?

File: examples/image-streamer/api300/plan_scripts.rb [hunk 4]
```diff
@@ -0,0 +1,59 @@
+# (C) Copyright 2016 Hewlett Packard Enterprise Development LP
```
Comment (tmiotto) [inline examples/image-streamer/api300/plan_scripts.rb]: Change copyright to 2017

File: lib/oneview-sdk/image-streamer/resource/api300/plan_scripts.rb [hunk 5]
```diff
@@ -17,6 +17,25 @@ module API300
...
+        # @param [Hash] params The options for this resource (key-value pairs)
+        # @param [Integer] api_ver The api version to use when interracting with this resource.
+        def initialize(client, params = {}, api_ver = nil)
+          super
+          # Default values:
+          @data['type'] ||= 'PlanScript'
+        end
+
+        # Retrieves the modified contents of the selected Plan Script as per the selected attributes.
+        # @return The script differences of the selected Plan Script
```
Comment (tmiotto) [inline lib/oneview-sdk/image-streamer/resource/api300/plan_scripts.rb]: The return is an array, string, hash...? Please specify in the comments

File: spec/integration/image-streamer/api300/plan_scripts/create_spec.rb [hunk 6]
```diff
@@ -0,0 +1,52 @@
+# (C) Copyright 2016 Hewlett Packard Enterprise Development LP
+#
```
Comment (tmiotto) [inline spec/integration/image-streamer/api300/plan_scripts/create_spec.rb]: Copyright

File: spec/integration/image-streamer/api300/plan_scripts/delete_spec.rb [hunk 7]
```diff
@@ -0,0 +1,26 @@
+# (C) Copyright 2016 Hewlett Packard Enterprise Development LP
```
Comment (tmiotto) [inline spec/integration/image-streamer/api300/plan_scripts/delete_spec.rb]: Copyright

File: spec/integration/image-streamer/api300/plan_scripts/update_spec.rb [hunk 8]
```diff
@@ -0,0 +1,17 @@
+require 'spec_helper'
+
+klass = OneviewSDK::ImageStreamer::API300::PlanScripts
+RSpec.describe klass, integration_i3s: true, type: UPDATE do
+  include_context 'integration i3s api300 context'
+
+  describe '#update' do
+    it 'updates the name of the plan script' do
+      item = klass.find_by($client_i3s_300, name: PLAN_SCRIPT1_NAME).first
+      expect(item['uri']).not_to be_empty
```
Comment (tmiotto) [inline spec/integration/image-streamer/api300/plan_scripts/update_spec.rb]: It's a bit weird expecting the URI to not be empty. If it exists it will never be empty, if doesn't exists it would be nil, and I really don't know if `NilClass#empty?` would return true.

File: spec/integration/sequence_and_naming.rb [hunk 9]
```diff
@@ -52,7 +52,8 @@ def tsort_each_child(node, &block)
   UplinkSet: [:LogicalInterconnectGroup, :LogicalInterconnect],
   Volume: [:StorageSystem, :StoragePool, :VolumeTemplate],
   VolumeAttachment: [:ServerProfile],
-  VolumeTemplate: [:StoragePool]
+  VolumeTemplate: [:StoragePool],
+  PlanScripts: []
```
Comment (tmiotto) [inline spec/integration/sequence_and_naming.rb]: Maybe we could split into another variable or file, what do you think?

File: spec/shared_context.rb [hunk 10]
```diff
@@ -109,6 +119,25 @@ def integration_context
   $config_synergy ||= OneviewSDK::Config.load(@config_path_synergy)
 end
 
+# Must set the following environment variables:
+#   ENV['ONEVIEWSDK_INTEGRATION_I3S_CONFIG'] = '/full/path/to/one_view/config.json'
+# Or use the default paths:
+#   spec/integration/one_view_i3s_config.json
+def integration_context_i3s
+  default_config = 'spec/integration/one_view_i3s_config.json'
+  @config_path_i3s ||= ENV['ONEVIEWSDK_INTEGRATION_I3S_CONFIG'] || default_config
```
Comment (tmiotto) [inline spec/shared_context.rb]: Do we reaaaally need to mention ONEVIEW in the Env? I mean, it's related to OneView but it isn't OneView...

File: spec/spec_helper.rb [hunk 11]
```diff
@@ -18,6 +18,8 @@
 SimpleCov.profiles.define 'integration' do
   add_filter 'spec/'
   add_filter 'cli.rb'
+  add_filter '../lib/oneview-sdk/image-streamer'
```
Comment (tmiotto) [inline spec/spec_helper.rb]: ???

File: spec/integration/image-streamer/api300/plan_scripts/update_spec.rb (hunk 8 above)
Comment (tmiotto) [inline spec/integration/image-streamer/api300/plan_scripts/update_spec.rb]: Now I know, the method really doesn't exist, so... fix it!

File: spec/spec_helper.rb (hunk 11 above)
Comment (aalexmonteiro) [inline spec/spec_helper.rb]: I put this line because I implemented the i3s integration tests to run separately from the others. When tests for oneview resources run, simplecov would ignore archives related to the i3s.

File: spec/integration/sequence_and_naming.rb (hunk 9 above)
Comment (aalexmonteiro) [inline spec/integration/sequence_and_naming.rb]: I was in doubt when I was doing this. But I think it's best to separate them. I will do this.

File: spec/spec_helper.rb (hunk 11 above)
Comment (tmiotto) [inline spec/spec_helper.rb]: Alright, so just add a `/` to the end of the filter, so we can clearly distinguish it is a folder

File: Rakefile (hunk 1 above)
Comment (aalexmonteiro) [inline Rakefile]: @tmiotto , I tried to run it with two tags, this way: `--tag integração --tag i3s`, but always run the other integration tests, not only for the i3s. It may be that I do not know the correct form. Do you have any suggestion?

**Comment by aalexmonteiro** [comment]
@tmiotto , I've made the requested changes, except the comment on the use of two tags. I added an answer on that. Please verify.

File: Rakefile (hunk 1 above)
Comment (tmiotto) [inline Rakefile]: Just leave it as is. Maybe we could open an issue to address this improvement.
