### PR TITLE
Enhanced API300::EnclosureGroup#add_logical_interconnect_group

### LINKED ISSUE #149: API300::Synergy::EnclosureGroup interconnectBayMappings dont't contain enclosureIndex
### Scenario/Intent
It is not possible to specify enclosureIndex when you are adding LIG to the EG with method *add_logical_interconnect_group*. It causes addition of the same LIG to all Synergy frames (inside the EG).

### Environment Details
 - **OneView API Version:** 300
- **api variant:** Synergy (& C7000)

### Steps to Reproduce
Create redundant *Virtual Connect SE 16Gb FC Module for Synergy* LIG (second bay set, bays 2&5) and try to add it to 3 Frames Enclosure Group (enclosureCount: 3).

### Actual Result
LIG is added to all Frames, so all three Frames have *Virtual Connect SE 16Gb FC Module for Synergy* LIG in bays 2&5.

actual_behaviour

### Expected Result
Addition of *Virtual Connect SE 16Gb FC Module for Synergy* LIG  to the certain Frame. So it should be possible to call add_logical_interconnect_group with optional parameter - enclosureIndex.

sample_of_expected_behaviour

### PR DESCRIPTION
**Pull request by jsmartt**
### Description
Allows you to specify which enclosures to apply the LIG settings for in the `#add_logical_interconnect_group` method.

To do this, we needed to expand the interconnectBayMappings to include entries for each enclosureIndex-interconnectBay combination. I added an optional parameter to the `#add_logical_interconnect_group` method that allows you to specify a specific enclosure to attach to the LIG, or if left out/nil, will attach to all enclosures (the old behavior). It will send an expanded set of interconnectBayMappings data to the API, but will match the old behavior in function, so I do not consider this a breaking change.

The only other change is updating a few of the methods in the EnclosureGroup resources to return the resource itself, not an indeterminate & uninteresting hash or array.

### Issues Resolved
Fixes #149

### Check List
- [x] New functionality includes testing.
  - [x] All tests pass (`$ rake test`).
- [x] New functionality has been documented in the README if applicable.
  - [x] New functionality has been thoroughly documented in the examples (please include helpful comments).
- [x] Changes are documented in the CHANGELOG.

### CODE REVIEW

**Comment by jsmartt** [comment]
@vranystepan, does this meet your expectations?

**Comment by vranystepan** [comment]
@jsmartt I've just done a few tests of functionality. It works perfectly. Thank you very much.

File: lib/oneview-sdk/resource/api300/c7000/enclosure_group.rb [hunk 1]
```diff
@@ -26,11 +26,64 @@ def initialize(client, params = {}, api_ver = nil)
...
           @data['type'] ||= 'EnclosureGroupV300'
           @data['stackingMode'] ||= 'Enclosure'
+          @data['enclosureCount'] ||= 1
           @data['interconnectBayMappingCount'] ||= 8
-          create_interconnect_bay_mapping unless @data['interconnectBayMappings']
           super
         end
 
+        # Adds the logical interconnect group
+        # @param [OneviewSDK::LogicalInterconnectGroup] lig Logical Interconnect Group
```
Comment (aalexmonteiro) [inline lib/oneview-sdk/resource/api300/c7000/enclosure_group.rb]: Should that be `OneviewSDK::API300::C7000::LogicalInterconnectGroup`?

File: lib/oneview-sdk/resource/api300/c7000/enclosure_group.rb [hunk 2]
```diff
@@ -26,11 +26,64 @@ def initialize(client, params = {}, api_ver = nil)
...
+        # @param [Integer] enclosureIndex Enclosure index of bay to add LIG to. If nil, interconnects will be added for all enclosures
+        # @raise [OneviewSDK::NotFound] if the LIG uri is not set and cannot be retrieved
+        # @return [OneviewSDK::EnclosureGroup] self
```
Comment (aalexmonteiro) [inline lib/oneview-sdk/resource/api300/c7000/enclosure_group.rb]: Should that be `OneviewSDK::API300::C7000::EnclosureGroup`?

File: lib/oneview-sdk/resource/api300/c7000/enclosure_group.rb [hunk 3]
```diff
@@ -26,11 +26,64 @@ def initialize(client, params = {}, api_ver = nil)
...
+            entry['logicalLocation']['locationEntries'].each do |location|
+              next unless location['type'] == 'Bay' && entry['permittedInterconnectTypeUri']
+              add_lig_to_bay(location['relativeValue'], lig, enclosureIndex)
+            end
+          end
+          self
+        end
+
+        # Creates the interconnect bay mapping
+        # @return [OneviewSDK::EnclosureGroup] self
```
Comment (aalexmonteiro) [inline lib/oneview-sdk/resource/api300/c7000/enclosure_group.rb]: Should that be `OneviewSDK::API300::C7000::EnclosureGroup`?

File: lib/oneview-sdk/resource/api300/c7000/enclosure_group.rb [hunk 4]
```diff
@@ -26,11 +26,64 @@ def initialize(client, params = {}, api_ver = nil)
...
+            end
+          end
+          self
+        end
+
+        private
+
+        # Add logical interconnect group to bay
+        # @param [Integer] bay Bay number
+        # @param [OneviewSDK::LogicalInterconnectGroup] lig Logical Interconnect Group
```
Comment (aalexmonteiro) [inline lib/oneview-sdk/resource/api300/c7000/enclosure_group.rb]: Should that be `OneviewSDK::API300::C7000::LogicalInterconnectGroup`?

File: lib/oneview-sdk/resource/api300/c7000/enclosure_group.rb (hunk 1 above)
Comment (jsmartt) [inline lib/oneview-sdk/resource/api300/c7000/enclosure_group.rb]: I've updated the return statements, but left these as-is because technically it can accept a `OneviewSDK::API200::LogicalInterconnectGroup`, `OneviewSDK::API300::C7000::LogicalInterconnectGroup`, or `OneviewSDK::API300::Synergy::LogicalInterconnectGroup` as a parameter. I wanted to keep it generic

Comment (aalexmonteiro) [inline lib/oneview-sdk/resource/api300/c7000/enclosure_group.rb]: Looks good. I agree.

File: lib/oneview-sdk/resource/api200/enclosure_group.rb [hunk 5]
```diff
@@ -49,16 +49,21 @@ def set_script(body)
 
       # Adds the logical interconnect group
       # @param [OneviewSDK::LogicalInterconnectGroup] lig Logical Interconnect Group
+      # @raise [OneviewSDK::NotFound] if the LIG uri is not set and cannot be retrieved
+      # @return [OneviewSDK::EnclosureGroup] self
       def add_logical_interconnect_group(lig)
         lig.retrieve! unless lig['uri']
+        raise(NotFound, 'LIG not found!') unless lig['uri']
```
Comment (tmiotto) [inline lib/oneview-sdk/resource/api200/enclosure_group.rb]: This message needs to be changed to something like:

```ruby
"The logical interconnect group #{lig['name']} was not found."
```

File: lib/oneview-sdk/resource/api300/c7000/enclosure_group.rb [hunk 6]
```diff
@@ -26,11 +26,64 @@ def initialize(client, params = {}, api_ver = nil)
...
         end
 
+        # Adds the logical interconnect group
+        # @param [OneviewSDK::LogicalInterconnectGroup] lig Logical Interconnect Group
+        # @param [Integer] enclosureIndex Enclosure index of bay to add LIG to. If nil, interconnects will be added for all enclosures
+        # @raise [OneviewSDK::NotFound] if the LIG uri is not set and cannot be retrieved
+        # @return [OneviewSDK::API300::C7000::EnclosureGroup] self
+        def add_logical_interconnect_group(lig, enclosureIndex = nil)
+          lig.retrieve! unless lig['uri']
+          raise(NotFound, 'LIG not found!') unless lig['uri']
```
Comment (tmiotto) [inline lib/oneview-sdk/resource/api300/c7000/enclosure_group.rb]: Same message here.

File: lib/oneview-sdk/resource/api300/c7000/enclosure_group.rb [hunk 7]
```diff
@@ -26,11 +26,64 @@ def initialize(client, params = {}, api_ver = nil)
...
+              next unless location['type'] == 'Bay' && entry['permittedInterconnectTypeUri']
+              add_lig_to_bay(location['relativeValue'], lig, enclosureIndex)
+            end
+          end
+          self
+        end
+
+        # Creates the interconnect bay mapping
+        # @return [OneviewSDK::API300::C7000::EnclosureGroup] self
+        def create_interconnect_bay_mapping
```
Comment (tmiotto) [inline lib/oneview-sdk/resource/api300/c7000/enclosure_group.rb]: Why is it being re-implemented here if it was removed?

File: lib/oneview-sdk/resource/api300/c7000/enclosure_group.rb [hunk 8]
```diff
@@ -26,11 +26,64 @@ def initialize(client, params = {}, api_ver = nil)
           # Default values:
           @data['type'] ||= 'EnclosureGroupV300'
           @data['stackingMode'] ||= 'Enclosure'
+          @data['enclosureCount'] ||= 1
           @data['interconnectBayMappingCount'] ||= 8
-          create_interconnect_bay_mapping unless @data['interconnectBayMappings']
```
Comment (tmiotto) [inline lib/oneview-sdk/resource/api300/c7000/enclosure_group.rb]: I guess the `@data['interconnectBayMappings']` still needs a default value like `[]`

File: lib/oneview-sdk/resource/api300/c7000/enclosure_group.rb (hunk 7 above)
Comment (jsmartt) [inline lib/oneview-sdk/resource/api300/c7000/enclosure_group.rb]: See above. It still gets called (from inside the API200 initialize method), but this overrides the behavior of the method.

File: lib/oneview-sdk/resource/api300/c7000/enclosure_group.rb (hunk 8 above)
Comment (jsmartt) [inline lib/oneview-sdk/resource/api300/c7000/enclosure_group.rb]: It does create it, since it calls super. See [here](https://github.com/HewlettPackard/oneview-sdk-ruby/blob/a9a639ca5adb08d17258ab4ac8a35ddd0a4df122/lib/oneview-sdk/resource/api200/enclosure_group.rb#L29).

File: spec/unit/resource/api300/c7000/enclosure_group_spec.rb [hunk 9]
```diff
@@ -45,4 +48,53 @@
       expect(item.set_script('Blah')).to eq(true)
     end
   end
+
+  describe '#create_interconnect_bay_mapping' do
+    it 'creates entries for each bay in each enclosure' do
```
Comment (jsmartt) [inline spec/unit/resource/api300/c7000/enclosure_group_spec.rb]: @tmiotto , this is the test that proves the mapping gets created on initialization.

File: lib/oneview-sdk/resource/api300/c7000/enclosure_group.rb (hunk 8 above)
Comment (tmiotto) [inline lib/oneview-sdk/resource/api300/c7000/enclosure_group.rb]: Oh, I totally missed the `super`, sorry. :open_mouth:
