### PR TITLE
Fix 231

### LINKED ISSUE #231: ServerProfile #add_connection overriding id
### Scenario/Intent
See [this](https://github.com/HewlettPackard/oneview-sdk-ruby/blob/master/lib/oneview-sdk/resource/api200/server_profile.rb#L168)

I'd like to be able to set the connection ID using the `#add_connection` method, but it overrides any value that I pass to the connection_options hash. It should be `||= 0` instead of `= 0`

Note: It also doesn't handle conversions of symbols, which we should fix here also. Use the steps to reproduce below to see what I mean.

### Environment Details
 - **OneView SDK Version:** 4.3.0

### Steps to Reproduce
```ruby
profile.add_connection(network, id: 1)
puts profile['connections']
```

### Expected Result
The connection id to be 1

### Actual Result
Connection id is 0

### PR DESCRIPTION
**Pull request by jsmartt**
### Description
Allow `ServerProfile#add_connection` to set an id.

### Issues Resolved
Fixes #231

### Check List
- [x] New functionality includes testing.
  - [x] All tests pass (`$ rake test`).
- [x] New functionality has been documented in the README if applicable.
  - [x] New functionality has been thoroughly documented in the examples (please include helpful comments).
- [x] Changes are documented in the CHANGELOG.

### CODE REVIEW

File: lib/oneview-sdk/resource/api200/server_profile.rb [hunk 1]
```diff
@@ -165,7 +166,7 @@ def get_available_hardware
       #   The value can be 'Virtual', 'Physical' or 'UserDefined'.
       def add_connection(network, connection_options = {})
         self['connections'] = [] unless self['connections']
-        connection_options['id'] = 0 # Letting OneView treat the ID registering
+        connection_options['id'] ||= 0 unless connection_options[:id] # Letting OneView treat the ID registering
```
Comment (fgbulsoni) [inline lib/oneview-sdk/resource/api200/server_profile.rb]: if we're using || do we need the unless here?
