### PR TITLE
Volume Attachment API 300 Support

### LINKED ISSUE #107: Volume Attachment API 300 Support
### Scenario/Intent
Use the Volume Attachment resource for API 300 C7000/Synergy.

### Environment Details
 - **OneView SDK Version: Future
 - **OneView Appliance Version: 300
 - **OneView Client API Version: 300
 - **Ruby Version: 2.2.3+
 - **Platform: w/e

### Steps to Reproduce
Trying to run the resource with the OneviewSDK::API300:::: syntax.

### Expected Result
Being able to call the resource methods and use it.

### Actual Result
It's currently not implemented, resulting in method unavailable.

### PR DESCRIPTION
**Pull request by ricardogpsf**
### Description
- Integration tests for api300
- Added more tests for api200

### Issues Resolved
Fixes #107 

### Check List
- [ ] New functionality includes testing.
  - [x] All tests pass (`$ rake test`).
- [ ] New functionality has been documented in the README if applicable.
  - [ ] New functionality has been thoroughly documented in the examples (please include helpful comments).
- [x] Changes are documented in the CHANGELOG.

### CODE REVIEW

File: spec/integration/resource/api200/volume_attachment/create_spec.rb [hunk 1]
```diff
@@ -0,0 +1,33 @@
...
+  end
+
+  describe '::get_extra_unmanaged_volumes' do
+    it 'should get the list of extra unmanaged storage volumes' do
+      expect { klass.get_extra_unmanaged_volumes($client) }.to_not raise_error
+    end
+  end
+
+  describe '::remove_extra_unmanaged_volume' do
+    xit 'should remove extra presentations from a specific server profile (Skipping this test because occurs error on the http method of ruby)' do
```
Comment (tmiotto) [inline spec/integration/resource/api200/volume_attachment/create_spec.rb]: Leave it failing

File: spec/integration/resource/api200/volume_attachment/update_spec.rb [hunk 2]
```diff
@@ -3,22 +3,10 @@
 RSpec.describe OneviewSDK::VolumeAttachment, integration: true, type: UPDATE do
   include_context 'integration context'
 
-  describe '#get_extra_unmanaged_volumes' do
```
Comment (tmiotto) [inline spec/integration/resource/api200/volume_attachment/update_spec.rb]: Why did you move all the*non-create* actions to the create_spec? It would be really good if they were here in *update_spec*.

File: spec/integration/resource/api300/c7000/volume_attachment/create_spec.rb [hunk 3]
```diff
@@ -0,0 +1,33 @@
...
+  end
+
+  describe '::get_extra_unmanaged_volumes' do
+    it 'should get the list of extra unmanaged storage volumes' do
+      expect { klass.get_extra_unmanaged_volumes($client_300) }.to_not raise_error
+    end
+  end
+
+  describe '::remove_extra_unmanaged_volume' do
+    xit 'should remove extra presentations from a specific server profile (Skipping this test because occurs error on the http method of ruby)' do
```
Comment (tmiotto) [inline spec/integration/resource/api300/c7000/volume_attachment/create_spec.rb]: Leave it failing

File: spec/integration/resource/api300/synergy/volume_attachment/create_spec.rb [hunk 4]
```diff
@@ -0,0 +1,33 @@
...
+  end
+
+  describe '::get_extra_unmanaged_volumes' do
+    it 'should get the list of extra unmanaged storage volumes' do
+      expect { klass.get_extra_unmanaged_volumes($client_300_synergy) }.to_not raise_error
+    end
+  end
+
+  describe '::remove_extra_unmanaged_volume' do
+    xit 'should remove extra presentations from a specific server profile (Skipping this test because occurs error on the http method of ruby)' do
```
Comment (tmiotto) [inline spec/integration/resource/api300/synergy/volume_attachment/create_spec.rb]: Leave it failing

**Comment by ricardogpsf** [comment]
@tmiotto cay you review again, please?

File: CHANGELOG.md [hunk 5]
```diff
@@ -32,6 +32,7 @@
    - Storage systems
    - Switches
    - Volume
+   - Volume attachment
```
Comment (tmiotto) [inline CHANGELOG.md]: Well, this resource should not be added on a tag that was already released, it should be in a new entry like *3.1.0*

**Comment by ricardogpsf** [comment]
@tmiotto cay you review again, please?
