### PR TITLE
The StoragePool of API500 can't be retrieved by name and storageSystemUri

### LINKED ISSUE #269: The StoragePool of API500 can't be retrieved using retrieve! method by name and storageSystemUri
### Scenario/Intent
The StoragePool of API500 can't be retrieved using `retrieve!` method by `name ` and `storageSystemUri`.
Using API200 ou API300 I can retrieve the StoragePool by name and `storageSystemUri` attributes, but this is not possible using StoragePool of API500.

### Steps to Reproduce
Try find StoragePool applying the `retrieve!` method with and StoragePool having the name and `storageSystemUri ` attributes.

### PR DESCRIPTION
**Pull request by ricardogpsf**
### Description
`retrieve!` method was overwrote into Storage Pool API500.

### Issues Resolved
Fixes #269 

### Check List
- [x] New functionality includes testing.
  - [x] All tests pass (`$ rake test`).
- [ ] New functionality has been documented in the README if applicable.
  - [ ] New functionality has been thoroughly documented in the examples (please include helpful comments).
- [x] Changes are documented in the CHANGELOG.

### CODE REVIEW

File: lib/oneview-sdk/resource/api500/c7000/storage_pool.rb [hunk 1]
```diff
@@ -40,6 +40,29 @@ def delete(*)
           unavailable_method
         end
 
+        # Retrieve resource details based on this resource's name or URI.
+        # @note Name or URI must be specified inside the resource
+        # @return [Boolean] Whether or not retrieve was successful
+        def retrieve!
+          raise IncompleteResource, 'Must set resource name or uri before trying to retrieve!' unless @data['name'] || @data['uri']
```
Comment (fgbulsoni) [inline lib/oneview-sdk/resource/api500/c7000/storage_pool.rb]: Shouldn't it be `(@data['name'] && @data['storageSystemUri']) || @data['uri']` ?
As it is it will not raise a failure in case the storageSystemUri is not passed in, is that the expected behavior?

Comment (ricardogpsf) [reply lib/oneview-sdk/resource/api500/c7000/storage_pool.rb]: Sure! I imaginated that the user could retrieve by name only, but really make no sense if storageSystemUri is not set because this shoud be the uniqueness attributes.
Thanks =)

File: lib/oneview-sdk/resource/api500/c7000/storage_pool.rb [hunk 2]
```diff
@@ -40,6 +40,29 @@ def delete(*)
...
+          if @data['name'] && @data['storageSystemUri']
+            results = self.class.find_by(@client, name: @data['name'], storageSystemUri: @data['storageSystemUri'])
+            if results.size == 1
+              set_all(results[0].data)
+              return true
+            end
+          end
+          super
```
Comment (fgbulsoni) [inline lib/oneview-sdk/resource/api500/c7000/storage_pool.rb]: Is there a point to calling `super` when we've already found the resource?
How about moving this to [line 48](https://github.com/HewlettPackard/oneview-sdk-ruby/pull/270/files#diff-c40ca7a34417c89fafffff2e3e5bfd96R48) as:
```ruby
return super if @data['uri']
```
After that you can assume that if you get past that code:
1- `@data['name'] && @data['storageSystemUri']` **are** both set 
2- `@data['uri']` **was not** set

Therefore you can go ahead and drop the `if @data['name'] && @data['storageSystemUri']` line.

Looks like that'd be cleaner, unless we want to be calling `super` in these cases for some reason I'm missing

File: lib/oneview-sdk/resource/api500/c7000/storage_pool.rb [hunk 3]
```diff
@@ -44,15 +45,13 @@ def delete(*)
         # @note Name or URI must be specified inside the resource
         # @return [Boolean] Whether or not retrieve was successful
         def retrieve!
-          raise IncompleteResource, 'Must set resource name or uri before trying to retrieve!' unless @data['name'] || @data['uri']
```
[the remark this answers is not in the document]
Comment (ricardogpsf) [reply lib/oneview-sdk/resource/api500/c7000/storage_pool.rb]: What do you think about this code?
```ruby
return super if @data['uri']
unless @data['name'] && @data['storageSystemUri']
  raise IncompleteResource, 'Must set resource name and storageSystemUri, or uri, before trying to retrieve!'
end
```
Must have the same result.

[the remark this answers is not in the document]
Comment (fgbulsoni) [reply lib/oneview-sdk/resource/api500/c7000/storage_pool.rb]: Seems fine
