### PR TITLE
Fix 'set_storage_pool' and 'set_snapshot_pool' methods in Volumes

### LINKED ISSUE #279: Bug when setting the Storage Pool and Snapshot Pool when trying to make an update
### Scenario/Intent
When I try to do a volume update and I use the ```set_storage_pool``` (API200, 300, 500) and ```set_snapshot_pool``` (API500) methods, error occurs, because the ```PUT``` request doesn't have the ```provisioningParameters``` (API200, 300) and ```properties``` (API500) attributes.

### Environment Details
 - **OneView SDK Version: current master repo
 - **OneView Appliance Version: Any
 - **OneView Client API Version: Any
 - **Ruby Version: 2.2.3+
 - **Platform: Any

### Steps to Reproduce
Try an update using the methods mentioned.

### Expected Result
Update successfully.

### Actual Result
Occurs a Bad Request 400.

### PR DESCRIPTION
**Pull request by aalexmonteiro**
### Description
Fix 'set_storage_pool' method for all APIS and 'set_snapshot_pool' method for API 500 in Volumes.

### Issues Resolved
#279 

### Check List
- [ ] New functionality includes testing.
  - [x] All tests pass (`$ rake test`).
- [ ] New functionality has been documented in the README if applicable.
  - [ ] New functionality has been thoroughly documented in the examples (please include helpful comments).
- [x] Changes are documented in the CHANGELOG.

### CODE REVIEW

File: lib/oneview-sdk/resource/api200/volume.rb [hunk 1]
```diff
@@ -68,11 +68,7 @@ def set_storage_system(storage_system)
       # @param [OneviewSDK::StoragePool] storage_pool Storage pool
       def set_storage_pool(storage_pool)
         assure_uri(storage_pool)
-        if self['provisioningParameters']
-          self['provisioningParameters']['storagePoolUri'] = storage_pool['uri']
-        else
-          self['storagePoolUri'] = storage_pool['uri']
```
Comment (tmiotto) [inline lib/oneview-sdk/resource/api200/volume.rb]: You've ommited this part in the new code. There is a reason why?

Comment (aalexmonteiro) [reply lib/oneview-sdk/resource/api200/volume.rb]: Because Ricardo commented that it is not possible to update a storage pool, I checked this in the documentation. Do you think the previous form is better?

File: lib/oneview-sdk/resource/api500/c7000/volume.rb [hunk 2]
```diff
@@ -62,16 +62,19 @@ def delete(flag = :all)
         # @param [OneviewSDK::StoragePool] storage_pool Storage pool.
         def set_storage_pool(storage_pool)
           assure_uri(storage_pool)
-          @data['properties'] ||= {}
-          @data['properties']['storagePool'] = storage_pool['uri']
+          @data['properties']['storagePool'] = storage_pool['uri'] if @data['properties']
```
Comment (tmiotto) [inline lib/oneview-sdk/resource/api500/c7000/volume.rb]: As far as it fixes the PUT it may break the POST.

File: lib/oneview-sdk/resource/api200/volume.rb (hunk 1 above)
Comment (tmiotto) [reply lib/oneview-sdk/resource/api200/volume.rb]: You are saying you cannot update by changing the Storage Pool associated with the volume, right?

File: lib/oneview-sdk/resource/api500/c7000/volume.rb (hunk 2 above)
Comment (tmiotto) [reply lib/oneview-sdk/resource/api500/c7000/volume.rb]: I'm concerned if it won't cause any breakage in already existing code

File: lib/oneview-sdk/resource/api200/volume.rb (hunk 1 above)
Comment (aalexmonteiro) [reply lib/oneview-sdk/resource/api200/volume.rb]: Yes! This property is read only.

File: lib/oneview-sdk/resource/api500/c7000/volume.rb (hunk 2 above)
Comment (aalexmonteiro) [reply lib/oneview-sdk/resource/api500/c7000/volume.rb]: I understand. Maybe another way would be inside the update method, delete the properties attribute. What do you think?

Comment (ricardogpsf) [reply lib/oneview-sdk/resource/api500/c7000/volume.rb]: Why not keeping the code how have been working before?
Because this helper method is just to be used before of the create (POST) action. For update, the user cannot set the storage_pool.
Maybe documenting that be sufficient.

File: lib/oneview-sdk/resource/api500/c7000/volume.rb [hunk 3]
```diff
@@ -62,16 +62,19 @@ def delete(flag = :all)
...
         end
 
         # Sets the snapshot pool to the volume
         # @param [OneviewSDK::StoragePool] storage_pool Storage Pool to use for snapshots.
         def set_snapshot_pool(storage_pool)
           assure_uri(storage_pool)
-          @data['properties'] ||= {}
-          @data['properties']['snapshotPool'] = storage_pool['uri']
+          if @data['properties']
```
Comment (ricardogpsf) [inline lib/oneview-sdk/resource/api500/c7000/volume.rb]: Maybe can be better check if this resource will be used to create a new resource or update the current resource, we can check if the 'uri' attribute is set.
And we should document this behavior.

File: spec/integration/shared_examples/volume/api200/update_snapshot_pool.rb [hunk 4]
```diff
@@ -0,0 +1,32 @@
...
+
+RSpec.shared_examples 'VolumeSnapshotPoolUpdateExample' do |context_name|
+  include_context context_name
+
+  let(:item) { described_class.find_by(current_client, name: VOLUME2_NAME).first }
+
+  describe '#update snapshot pool' do
+    it 'updating the snapshot pool' do
+      old_snapshot_pool = resource_class_of('StoragePool').find_by(current_client, uri: item['snapshotPoolUri']).first
+      new_snapshot_pool = resource_class_of('StoragePool').get_all(current_client).first
```
Comment (ricardogpsf) [inline spec/integration/shared_examples/volume/api200/update_snapshot_pool.rb]: It can occur of same storage_pool be returned by those two calls?

File: spec/integration/shared_examples/volume/api500/create.rb [hunk 5]
```diff
@@ -231,18 +231,30 @@
...
+      item = described_class.new(current_client, name: VOLUME_NAME, properties: {})
+      item.set_storage_pool(storage_pool)
+      expect(item['properties']['storagePool']).to eq(storage_pool['uri'])
+    end
+
     it 'set_storage_pool' do
       item = described_class.new(current_client, name: VOLUME_NAME)
       item.set_storage_pool(storage_pool)
-      expect(item['properties']['storagePool']).to eq(storage_pool['uri'])
+      expect(item['storagePoolUri']).to eq(storage_pool['uri'])
```
Comment (ricardogpsf) [inline spec/integration/shared_examples/volume/api500/create.rb]: But the result of `set_storage_pool ` should have set the `['properties']['storagePool']`, because it is the test of create action, right?! For create action, the URI of storage pool should be inside `item['properties']['storagePool']`.

File: spec/integration/shared_examples/volume/api500/create.rb [hunk 6]
```diff
@@ -231,18 +231,30 @@
...
+      item = described_class.new(current_client, name: VOLUME_NAME, properties: {})
+      item.set_snapshot_pool(storage_pool)
+      expect(item['properties']['snapshotPool']).to eq(storage_pool['uri'])
+    end
+
     it 'set_snapshot_pool' do
       item = described_class.new(current_client, name: VOLUME_NAME)
       item.set_snapshot_pool(storage_pool)
-      expect(item['properties']['snapshotPool']).to eq(storage_pool['uri'])
+      expect(item['snapshotPoolUri']).to eq(storage_pool['uri'])
```
Comment (ricardogpsf) [inline spec/integration/shared_examples/volume/api500/create.rb]: same case of my last comment.

File: spec/integration/shared_examples/volume/create.rb [hunk 7]
```diff
@@ -112,10 +112,16 @@
...
+      item = described_class.new(current_client, name: VOLUME_NAME, provisioningParameters: {})
+      item.set_storage_pool(storage_pool)
+      expect(item['provisioningParameters']['storagePoolUri']).to eq(storage_pool['uri'])
+    end
+
     it 'set_storage_pool' do
       item = described_class.new(current_client, name: VOLUME_NAME)
       item.set_storage_pool(storage_pool)
-      expect(item['provisioningParameters']['storagePoolUri']).to eq(storage_pool['uri'])
+      expect(item['storagePoolUri']).to eq(storage_pool['uri'])
```
Comment (ricardogpsf) [inline spec/integration/shared_examples/volume/create.rb]: same case of my last comment.

File: spec/unit/resource/api500/c7000/volume_spec.rb [hunk 8]
```diff
@@ -87,19 +87,31 @@
...
+      item.set_storage_pool(OneviewSDK::StoragePool.new(@client_500, uri: '/rest/fake'))
+      expect(item['storagePoolUri']).to_not be
+    end
   end
 
   describe '#set_snapshot_pool' do
-    it 'sets the snapshotPool attribute' do
-      item = described_class.new(@client_500)
+    it 'sets the snapshotPool attribute in properties' do
+      item = described_class.new(@client_500, properties: {})
```
Comment (ricardogpsf) [inline spec/unit/resource/api500/c7000/volume_spec.rb]: if the user are not pass the properties as an empty `Hash` and set the storate_pool, will the create action create a Volume with that storage pool associated? If not, is this behavior correct?
For me, no problem use this new approach, but maybe important documenting that over the constructor of the Volume class.

File: spec/unit/resource/api500/c7000/volume_spec.rb [hunk 9]
```diff
@@ -87,19 +87,31 @@
...
       item.set_snapshot_pool(OneviewSDK::StoragePool.new(@client_500, uri: '/rest/fake'))
       expect(item['properties']['snapshotPool']).to eq('/rest/fake')
     end
+
+    it 'sets the snapshotPoolUri attribute' do
+      item = described_class.new(@client_500, deviceSpecificAttributes: {})
```
Comment (ricardogpsf) [inline spec/unit/resource/api500/c7000/volume_spec.rb]: same case of my last comment.

File: spec/integration/shared_examples/volume/api500/create.rb (hunk 5 above)
Comment (ricardogpsf) [reply spec/integration/shared_examples/volume/api500/create.rb]: no problem. That things happen. 😄

File: lib/oneview-sdk/resource/api500/c7000/volume.rb (hunk 3 above)
Comment (aalexmonteiro) [reply lib/oneview-sdk/resource/api500/c7000/volume.rb]: But if the user is trying to create something that already exists or in the case of the 'get_volume_template_uri' method I can assign a storage_pool without the properties attribute? I think it better to do the update treatment as it is done in the create.

Comment (ricardogpsf) [reply lib/oneview-sdk/resource/api500/c7000/volume.rb]: > But if the user is trying to create something that already exists 

I did not understand the reason for this.

> the case of the 'get_volume_template_uri' method I can assign a storage_pool without the properties attribute?

but the `get_volume_template_uri` method seems getting the value from correct place:
```ruby
 def get_volume_template_uri(template_data)
   storage_pool_uri = self['storagePoolUri'] || self['properties']['storagePool']
   ...
```

Comment (aalexmonteiro) [reply lib/oneview-sdk/resource/api500/c7000/volume.rb]: Ok! Maybe that can solve. ```@data['properties'] ||= {} unless @data['uri']```

Because it does not make much sense for me to check the existence of a volume in this method. If uri was passed, I assume user knows that the resource already exists.

**Comment by aalexmonteiro** [comment]
@ricardogpsf , I removed one comment, which was a replica of another comment I made, but then I saw that it did not make sense. So I removed mine and to make it cleaner, I also removed yours.
