### PR TITLE
Uplink Set API 300 Support

### LINKED ISSUE #108: Uplink Set API 300 Support
### Scenario/Intent
Use Uplink Sets calls in API300.

### Environment Details
 - **OneView SDK Version: Future
 - **OneView Appliance Version: 300
 - **OneView Client API Version: 300
 - **Ruby Version: 2.2.3+
 - **Platform: w/e

### Steps to Reproduce
Try using Uplink Sets calls in API300.

### Expected Result
Methods are available and working.

### Actual Result
Currently not implemented / method unavailable.

### PR DESCRIPTION
**Pull request by ricardogpsf**
### Description
New method for api200
Integration tests for api300

### Issues Resolved
Fixes #108 

### Check List
- [x] New functionality includes testing.
  - [x] All tests pass (`$ rake test`).
- [ ] New functionality has been documented in the README if applicable.
  - [x] New functionality has been thoroughly documented in the examples (please include helpful comments).
- [x] Changes are documented in the CHANGELOG.

### CODE REVIEW

File: lib/oneview-sdk/resource/api200/uplink_set.rb [hunk 1]
```diff
@@ -78,6 +85,13 @@ def add_fcoenetwork(network)
         raise IncompleteResource, 'Must set network uri attribute' unless uri
         @data['fcoeNetworkUris'].push(uri)
       end
+
+      # Gets the unassigned uplink ports
+      def get_unassigned_ports
```
Comment (ricardogpsf) [inline lib/oneview-sdk/resource/api200/uplink_set.rb]: This method is not in rest api documentation, but is an important feature.

File: lib/oneview-sdk/resource/api300/synergy/uplink_set.rb [hunk 2]
```diff
@@ -14,7 +14,18 @@
 module OneviewSDK
   module API300
     module Synergy
+      # Uplink set resource implementation for API300 Thunderbird
```
Comment (aalexmonteiro) [inline lib/oneview-sdk/resource/api300/synergy/uplink_set.rb]: Replaces Thunderbird by Synergy.

File: lib/oneview-sdk/resource/api300/c7000/uplink_set.rb [hunk 3]
```diff
@@ -14,7 +14,19 @@
...
+      # Uplink set resource implementation for API300 C7000
       class UplinkSet < OneviewSDK::API200::UplinkSet
+
+        # Create a resource object, associate it with a client, and set its properties.
+        # @param [OneviewSDK::Client] client The client object for the OneView appliance
+        # @param [Hash] params The options for this resource (key-value pairs)
+        # @param [Integer] api_ver The api version to use when interracting with this resource.
+        def initialize(client, params = {}, api_ver = nil)
+          # Default values for api300
+          params[:type] ||= params['type'] ||= 'uplink-setV300'
```
Comment (fgbulsoni) [inline lib/oneview-sdk/resource/api300/c7000/uplink_set.rb]: Instead of params, use @data['type'] ||= 'uplink-setV300'
Also, no need for using the symbol as well.

File: lib/oneview-sdk/resource/api300/synergy/uplink_set.rb [hunk 4]
```diff
@@ -14,7 +14,18 @@
...
+      # Uplink set resource implementation for API300 Synergy
       class UplinkSet < OneviewSDK::API200::UplinkSet
+
+        # Create a resource object, associate it with a client, and set its properties.
+        # @param [OneviewSDK::Client] client The client object for the OneView appliance
+        # @param [Hash] params The options for this resource (key-value pairs)
+        # @param [Integer] api_ver The api version to use when interracting with this resource.
+        def initialize(client, params = {}, api_ver = nil)
+          # Default values for api300
+          params[:type] ||= params['type'] ||= 'uplink-setV300'
```
Comment (fgbulsoni) [inline lib/oneview-sdk/resource/api300/synergy/uplink_set.rb]: Instead of params, use @data['type'] ||= 'uplink-setV300'
Also, no need for using the symbol as well.

File: lib/oneview-sdk/resource/api200/uplink_set.rb [hunk 5]
```diff
@@ -32,6 +32,13 @@ def initialize(client, params = {}, api_ver = nil)
         @data['type'] ||= 'uplink-setV3'
       end
 
+      # Gets the JSON schema
+      # @param [OneviewSDK::Client] client The client object for the OneView appliance
+      def self.get_schema(client)
```
Comment (fgbulsoni) [inline lib/oneview-sdk/resource/api200/uplink_set.rb]: Schemas are considered Out of Scope, should remove

File: lib/oneview-sdk/resource/api200/uplink_set.rb (hunk 1 above)
Comment (ricardogpsf) [inline lib/oneview-sdk/resource/api200/uplink_set.rb]: In the Oneview UI, when I will create a new uplink to a logical interconnect, a request is did using that URI to get the unassigned ports.

Comment (fgbulsoni) [inline lib/oneview-sdk/resource/api200/uplink_set.rb]: Ok, makes sense to implement it if the UI also uses it. 
Still needs expected ``@return``/``@params`` comments for documentation.

Comment (ricardogpsf) [inline lib/oneview-sdk/resource/api200/uplink_set.rb]: ok. I will push a new commit with the changes. =)

File: examples/_client.rb.example [hunk 6]
```diff
@@ -36,3 +36,5 @@ puts "Connected to OneView appliance at #{@client.url}\n\n"
 # @firmware_bundle_path = 'hp-firmware-a1b08f8a6b-HPGH-1.1.i386.rpm'
 # @sas_interconnect_type = 'Synergy 12Gb SAS Connection Module'
 # @synergy_enclosure_hostname = 'fe80::2:0:9:1%eth2'
+# @enclosure_name = '0000A66101'
+# @interconnect_name = '0000A66101, interconnect 3'
```
Comment (ricardogpsf) [inline examples/_client.rb.example]: I think so not.
Because that more than one interconnect can be created automatically (after add a new enclosure, for C7000), and some them can't used for create a new uplink, this iwas the reason I put the interconnect_name.
And more than one Enclosure can be added automatically (for Synergy), and it was the reason I put enclosure_name.
I'm using DCS.

File: examples/api200/uplink_set.rb [hunk 7]
```diff
@@ -9,33 +9,58 @@
 # CONDITIONS OF ANY KIND, either express or implied. See the License for the
 # specific language governing permissions and limitations under the License.
 
-require_relative '../_client'
+require_relative '../_client' # Gives access to @client, @enclosure_name, @interconnect_name
 
-ethernet = OneviewSDK::EthernetNetwork.new(@client, name: 'lig_eth01')
-ethernet.retrieve!
-puts "Ethernet uri = '#{ethernet[:uri]}'"
+# NOTE: This will create a uplink set named 'Teste Uplink', then update it with network, then delete it.
```
Comment (fgbulsoni) [inline examples/api200/uplink_set.rb]: (...) named 'UplinkSet Example' (...)

File: examples/_client.rb.example (hunk 6 above)
Comment (fgbulsoni) [inline examples/_client.rb.example]: Ok. I'd recommend moving the @enclosure_name to the line before enclosure_hostname in that case. Other than that looks fine. 
Thoughts on this solution @tmiotto, @jsmartt ?

Comment (jsmartt) [inline examples/_client.rb.example]: If the enclosure and interconnect can't be retrieved automatically, I'd say it's fine to keep that in the _client.rb.example file. However, I'm wondering if it can be retrieved automatically though; can we get the whole list of enclosures, and select the first one that will work? I'm not sure exactly what determines whether or not it will work, but I'm assuming we can determine that programatically if we can do it manually.

And I agree that all related variables (including the enclosure ones) should be kept together. Grouping will make it easier to fill out/update.

Comment (ricardogpsf) [inline examples/_client.rb.example]: Yes, it is possible determine the correct data that I want work with example, but is more complex that simply get by name. I thought about using variables because is more simple to get the data, but if it is better keep less variables even that example become a litle more complex, no problem for me. =)

Comment (jsmartt) [inline examples/_client.rb.example]: Whatever you think is best works for me. I see the reasons to use either solution

File: CHANGELOG.md [hunk 8]
```diff
@@ -1,3 +1,7 @@
+# v3.1.0
+ 1. Added full support to OneView Rest API version 300 for the hardware variants C7000 and Synergy to the already existing features:
+   - Uplink Set
+
```
Comment (fgbulsoni) [inline CHANGELOG.md]: It's probably good to also add:

### Features supported
   - Connection template
   - Datacenter
   - Enclosure
   - Ethernet network
   - Fabrics
   - FC network
   - FCoE network
   - Firmware bundles
   - Firmware drivers
   - Logical downlink
   - Logical enclosure
   - Logical interconnect
   - Logical interconnect Group
   - Uplink Set
   - Logical switch
   - Logical switch group
   - Managed SANs
   - Network set
   - Power devices
   - Racks
   - SAN managers
   - Server hardware
   - Server hardware type
   - Server profile
   - Server profile template
   - Storage pools
   - Storage systems
   - Switches
   - Volume
   - Volume template
   - Drive Enclosures
   - Interconnect Link Topology
   - Internal Link Set
   - SAS Interconnect
   - SAS Interconnect Type
   - SAS Logical Interconnect
   - SAS Logical Interconnect Group
   - SAS Logical JBOD Attachments
   - SAS Logical JBODs

So that this list can contain everything that is supported by this full support release.

File: CHANGELOG.md [hunk 9]
```diff
@@ -31,6 +31,7 @@
    - Storage pools
    - Storage systems
    - Switches
+   - Uplink Set
```
Comment (fgbulsoni) [inline CHANGELOG.md]: This should still be removed from here
