### PR TITLE
Fixing overridden methods not receiving header parameter

### LINKED ISSUE #294: Overridden methods without receiving header parameter
### Scenario/Intent
I'm trying to delete a API300::C7000::Scope passing a header as a parameter, but I can't and the default code fails (Resource#create!).

### Environment Details
 - **OneView SDK Version:** 5.2.0
 - **OneView Client API Version:** API300

### Steps to Reproduce
Run  API300::C7000::Scope#create!

### Expected Result
The scope should be deleted and created successfully

### Actual Result
It fails saying the delete won't receive any arguments (the header)

### Root cause
API300::C7000::Scope is overriding the delete without parameters, so it is causing it to fail.

### PR DESCRIPTION
**Pull request by aalexmonteiro**
### Description
Fixing overridden methods(create, retrieve!, delete) not receiving header parameter.

### Issues Resolved
#294

### Check List
- [ ] New functionality includes testing.
  - [x] All tests pass (`$ rake test`).
- [ ] New functionality has been documented in the README if applicable.
  - [ ] New functionality has been thoroughly documented in the examples (please include helpful comments).
- [ ] New endpoints supported are updated in the endpoints-support.md file.
- [x] Changes are documented in the CHANGELOG.

### CODE REVIEW

**Comment by aalexmonteiro** [comment]
@fgbulsoni , I tried to put some headers with the default value. But I saw that I also needed to replace the ```creation!``` method. So I guess this doesn't look cool. What do you think?

File: lib/oneview-sdk/resource/api200/volume_template.rb [hunk 1]
```diff
@@ -33,23 +33,19 @@ def initialize(client, params = {}, api_ver = nil)
...
       # @raise [OneviewSDK::IncompleteResource] if the client is not set
       # @raise [StandardError] if the resource creation fails
       # @return [Resource] self
-      def create
-        ensure_client
-        response = @client.rest_post(self.class::BASE_URI, { 'Accept-Language' => 'en_US', 'body' => @data }, @api_version)
-        body = @client.response_handler(response)
-        set_all(body)
+      def create(header = DEFAULT_REQUEST_HEADER)
+        super(header.merge('Accept-Language' => 'en_US'))
```
Comment (fgbulsoni) [inline lib/oneview-sdk/resource/api200/volume_template.rb]: Isn't it worth it to add `'Accept-Language' => 'en_US'` to `def create(header = DEFAULT_REQUEST_HEADER)`?
As in, `def create(header = {'Accept-Language' => 'en_US'})`

**Comment by tmiotto** [comment]
I actually have a suggestion.

It would have been more compliant with best practices if instead setting the default header to {}, expecting user to pass something or defaulting it to the default header, and merging with a actual default value, i.e.:
```ruby
DEFAULT_REQUEST_HEADER = {}
def create(header = DEFAULT_REQUEST_HEADER)
        super(header.merge('Accept-Language' => 'en_US'))
```
Actually using this actual default value in the default header, and merging it always with the parameter header, i.e.:
```ruby
DEFAULT_REQUEST_HEADER = { 'Accept-Language' => 'en_US' }
def create(header = {})
        super(header.merge(DEFAULT_REQUEST_HEADER))
```

This way the default header would make sense to exist, because right now it is a simple constant that actually does nothing.

**Comment by aalexmonteiro** [comment]
@tmiotto , Your suggestion helped me and I did it in a way that I think has gotten better.

File: lib/oneview-sdk/resource/api200/volume_template.rb [hunk 2]
```diff
@@ -38,14 +39,14 @@ def initialize(client, params = {}, api_ver = nil)
...
-        super(header.merge('Accept-Language' => 'en_US'))
+        super(header)
       end
 
       # Deletes the volume template from OneView
       # @param [Hash] header The header options for the request (key-value pairs)
       # @return [TrueClass] if the volume template was deleted successfully
       def delete(header = DEFAULT_REQUEST_HEADER)
-        super(header.merge('Accept-Language' => 'en_US'))
+        super(header)
```
Comment (tmiotto) [inline lib/oneview-sdk/resource/api200/volume_template.rb]: If you are following my suggestion I guess you would still need to merge the `header` with the `DEFAULT_REQUEST_HEADER`, otherwise default values may be overwritten.
```Ruby
def create(header = {})
  super(header.merge(DEFAULT_REQUEST_HEADER))
```

**Comment by fgbulsoni** [comment]
Overall, since it LGTM.

Looks like the `header.merge(DEFAULT_REQUEST_HEADER)` requested have been added in the latest commit, and I don't see any particular issue with the code.

Merging it.
