### PR TITLE
Changing the 'add' method in Volume API500

### LINKED ISSUE #275: Method 'add' in Volume API 500 expects different arguments from usual 'add' implementations.
### Scenario/Intent
Currently, the add method in Volume is necessary to pass some parameters. But the standard way to use the add method in the Ruby SDK is through the hash data.

### Environment Details
 - **OneView SDK Version: current master repo
 - **OneView Appliance Version: Any
 - **OneView Client API Version: Any
 - **Ruby Version: 2.2.3+
 - **Platform: Any

### Steps to Reproduce
N/A

### Expected Result
Be able to pass the hash of data.

### Actual Result
Is necessary to pass some parameters in add method.

### PR DESCRIPTION
**Pull request by aalexmonteiro**
### Description
Currently, the add method in Volume is necessary to pass some parameters. The add method was modified for  standard way to use the add method in the Ruby SDK using the hash data.

### Issues Resolved
#275 

### Check List
- [] New functionality includes testing.
  - [x] All tests pass (`$ rake test`).
- [ ] New functionality has been documented in the README if applicable.
  - [x] New functionality has been thoroughly documented in the examples (please include helpful comments).
- [x] Changes are documented in the CHANGELOG.

### CODE REVIEW

File: examples/api500/volume.rb [hunk 1]
```diff
@@ -123,10 +123,14 @@
 
 options5 = {
   'name' => 'ONEVIEW_SDK_TEST_VOLUME_5',
-  'description' => 'adding a volume'
+  'description' => 'Volume added',
```
Comment (fgbulsoni) [inline examples/api500/volume.rb]: Probably good to use symbols here.
```ruby
description: 'Volume added',
(...)
```

File: lib/oneview-sdk/resource/api500/c7000/volume.rb [hunk 2]
```diff
@@ -111,20 +111,16 @@ def create_from_snapshot(snapshot_name, properties, volume_template = nil, is_pe
...
         # @return [OneviewSDK::Volume] The volume imported.
-        def self.add(client, storage_system, volume_name, is_shareable = false, options = {})
-          raise IncompleteResource, 'Storage system not found!' unless storage_system.retrieve!
-          data = options.merge('storageSystemUri' => storage_system['uri'], 'deviceVolumeName' => volume_name, 'isShareable' => is_shareable)
-          response = client.rest_post("#{BASE_URI}/from-existing", { 'body' => data }, client.api_version)
-          new(client, client.response_handler(response))
+        def add
+          ensure_client
+          required_attributes = %w(deviceVolumeName isShareable storageSystemUri)
+          required_attributes.each { |k| raise IncompleteResource, "Missing required attribute: '#{k}'" unless @data.key?(k) }
```
Comment (fgbulsoni) [inline lib/oneview-sdk/resource/api500/c7000/volume.rb]: So we can also accept symbols:
```
(...) unless @data.key?(k.to_s)
```

**Comment by fgbulsoni** [comment]
Nice, just drop the unreleased as I'm assuming this will be released right away to be used with Chef.

File: CHANGELOG.md [hunk 3]
```diff
@@ -1,3 +1,8 @@
+# v6.0.0(unreleased)
```
Comment (fgbulsoni) [inline CHANGELOG.md]: Nice, just drop this unreleased and bump up versions as I'm assuming this will be released right away to be used with Chef.

File: lib/oneview-sdk/resource/api500/c7000/volume.rb [hunk 4]
```diff
@@ -111,20 +111,16 @@ def create_from_snapshot(snapshot_name, properties, volume_template = nil, is_pe
...
-        # @option options [String] :description The description for new volume.
-        # @raise [OneviewSDK::IncompleteResource] if storage system is not found
+        # @raise [OneviewSDK::IncompleteResource] if the client is not set or required attributes are missing
         # @return [OneviewSDK::Volume] The volume imported.
-        def self.add(client, storage_system, volume_name, is_shareable = false, options = {})
-          raise IncompleteResource, 'Storage system not found!' unless storage_system.retrieve!
-          data = options.merge('storageSystemUri' => storage_system['uri'], 'deviceVolumeName' => volume_name, 'isShareable' => is_shareable)
-          response = client.rest_post("#{BASE_URI}/from-existing", { 'body' => data }, client.api_version)
-          new(client, client.response_handler(response))
+        def add
```
[the remark this answers is not in the document]
Comment (fgbulsoni) [reply lib/oneview-sdk/resource/api500/c7000/volume.rb]: Sounds fine, will eventually be a breaking change since it should be removed, but does not need to be *now*.

[the remark this answers is not in the document]
Comment (aalexmonteiro) [reply lib/oneview-sdk/resource/api500/c7000/volume.rb]: @tmiotto , @fgbulsoni . Although I have merged, I did not post to Rubygems. In this case would the release be 5.0.6 or 6.0.0?
