### PR TITLE
OS Volume i3s API300 Support

### LINKED ISSUE #121: I3S - OS Volumes API 300 Support
### Scenario/Intent
Use the Image Streamer - OS Volumes resource for API 300 C7000/Synergy.

### Environment Details
 - **OneView SDK Version: Future
 - **OneView Appliance Version: 300
 - **OneView Client API Version: 300
 - **Ruby Version: 2.2.3+
 - **Platform: w/e

### Steps to Reproduce
Trying to run the resource of Image Streamer for API 300.

### Expected Result
Being able to call the resource methods and use it.

### Actual Result
It's currently not implemented.

### PR DESCRIPTION
**Pull request by aalexmonteiro**
### Description
Implementation of the os volumes for i3s API300 support.

### Issues Resolved
#121 

### Check List
- [x] New functionality includes testing.
  - [x] All tests pass (`$ rake test`).
- [ ] New functionality has been documented in the README if applicable.
  - [x] New functionality has been thoroughly documented in the examples (please include helpful comments).
- [x] Changes are documented in the CHANGELOG.

### CODE REVIEW

**Comment by aalexmonteiro** [comment]
Note: The integration tests and example for `get_details_archive`  is not working properly due to bug in i3s appliance.

File: lib/oneview-sdk/image-streamer/resource/api300/os_volumes.rb [hunk 1]
```diff
@@ -17,6 +17,32 @@ module API300
       # OS Volumes resource implementation for Image Streamer
       class OsVolumes < Resource
```
Comment (jsmartt) [inline lib/oneview-sdk/image-streamer/resource/api300/os_volumes.rb]: 2 comments:
1.  Should this be `OSVolumes` instead of `OsVolumes`. The "S" is usually capitalized in OS. I understand that camelCase makes it a little weird, but we do it in other resources (e.g., 'SANManager')
2. CHANGELOG update?

Comment (aalexmonteiro) [inline lib/oneview-sdk/image-streamer/resource/api300/os_volumes.rb]: @jsmartt , I will correct the name class.

Regarding CHANGELOG, what was decided on the release? Will one soon be released with bugfix and enhancements or will they wait for the i3s features?

Comment (jsmartt) [inline lib/oneview-sdk/image-streamer/resource/api300/os_volumes.rb]: My vote would be to release soon, but IDK what other people's thoughts are

**Comment by aalexmonteiro** [comment]
@jsmartt , the OSVolumes class renamed and CHANGELOG updated with the new features of the i3s.

File: lib/oneview-sdk/image-streamer/resource/api300/os_volumes.rb [hunk 2]
```diff
@@ -15,8 +15,34 @@ module OneviewSDK
   module ImageStreamer
     module API300
       # OS Volumes resource implementation for Image Streamer
-      class OsVolumes < Resource
+      class OSVolumes < Resource
```
Comment (marikrg) [inline lib/oneview-sdk/image-streamer/resource/api300/os_volumes.rb]: Why are you using plural for OSVolumes?
I noticed that usually the names of the resources' classes on the Ruby SDK are in singular.

**Comment by aalexmonteiro** [comment]
@marikrg , the class renamed as well as the files.

File: lib/oneview-sdk/image-streamer/resource/api300/os_volume.rb [hunk 3]
```diff
@@ -0,0 +1,49 @@
...
+module OneviewSDK
+  module ImageStreamer
+    module API300
+      # OS Volume resource implementation for Image Streamer
+      class OSVolume < Resource
+        BASE_URI = '/rest/os-volumes'.freeze
+
+        # Method is not available
+        # @raise [OneviewSDK::MethodUnavailable] method is not available
+        def create
```
Comment (jsmartt) [inline lib/oneview-sdk/image-streamer/resource/api300/os_volume.rb]: For all these methods that call `unavailable_method`, let's let them take any arguments. See #155.

Otherwise it looks good to me. However, I have no I3S appliance to test against, so I'll let someone else give the final 👍

Comment (aalexmonteiro) [inline lib/oneview-sdk/image-streamer/resource/api300/os_volume.rb]: @jsmartt , Jared, we only have one available test device that is running and a hardware in India.

**Comment by aalexmonteiro** [comment]
@jsmartt , changes made.

**Comment by ricardogpsf** [comment]
Looks good for me.

**Comment by jsmartt** [comment]
I say let's :shipit: . What do you think @aalexmonteiro ?

**Comment by aalexmonteiro** [comment]
Note: The integration tests and example for get_details_archive is not working properly due to bug in i3s appliance.
