### PR TITLE
Simplify login to i3s through oneview client

### LINKED ISSUE #166: I3S - Simplify login to i3s through oneview client
### Scenario/Intent
As far as I can see, currently I'm able to authenticate on Image Streamer only using a token
I have tried to access with an username/password and I got the error: `Must set token option`

From the tools point of view, may be better for some of them authenticate with username/password. The token expires frequently and the tools doesn't provide (and I believe it shouldn't) a way to generate it.

Then, it shouldn't be supported by ImageStreamer client?

### Environment Details
 - **OneView SDK Version:** current master repo
 - **OneView Appliance Version:** OneView 3.0 (Synergy)
 - **OneView Client API Version:** 300
 - **Ruby Version:** Any
 - **Platform:** Any

### Steps to Reproduce
1. Define username/password instead of token
2. Instantiate the ImageStreamer Client.
3. Error `Must set token option` is raised.

### Expected Result
Possible solution:
1. Define username/password instead of a token
2. Instantiate the ImageStreamer Client.
3. Authenticate against OneView appliance and uses the generated token for ImageStreamer rest calls (as a single sign-on).

### Actual Result
[What *actually* happens after the steps above? Include error output or a link to a gist.]

### PR DESCRIPTION
**Pull request by aalexmonteiro**
### Description
Implementation of login to i3s through oneview client.

### Issues Resolved
#166 

### Check List
- [x] New functionality includes testing.
  - [x] All tests pass (`$ rake test`).
- [x] New functionality has been documented in the README if applicable.
  - [x] New functionality has been thoroughly documented in the examples (please include helpful comments).
- [x] Changes are documented in the CHANGELOG.

### CODE REVIEW

File: examples/_client_i3s.rb.example [hunk 1]
```diff
@@ -7,6 +8,20 @@ require 'pry'
   token: 'token_oneview', # or set ENV['I3S_TOKEN']
   ssl_enabled: false
 )
+
+# Another way to instantiate the i3s client. Uncomment the creation of onv_client and @client instances.
+# onv_client = OneviewSDK::Client.new(
```
Comment (tmiotto) [inline examples/_client_i3s.rb.example]: OneView official abbreviation is *ov*

**Comment by aalexmonteiro** [comment]
@tmiotto , changes made.
