### PR TITLE
Fix 'like?' method for Logical Interconnect Groups

### LINKED ISSUE #89: Fix like? method for Logical Interconnect Groups
Default `like?` method is not working properly for Logical Interconnect Groups with Interconnects attached and Uplinks Sets defined.
- oneview-ruby-sdk version:  2.x

### PR DESCRIPTION
**Pull request by ricardogpsf**
### Description
The `like?` method of Resource class does not can compare arrays correctly. For this, when it compare two Logical Interconnect Groups that have uplinkSets and Interconnects (that are arrays of objects), the `like?` method returns false (it should return true).
This commit changes the method `like?` for accept an object with attributes that are arrays and compare them with the respective resource attribute.

### Issues Resolved
Fixes #89 

### Check List
- [x] New functionality includes testing.
  - [x] All tests pass (`$ rake test`).
- [ ] New functionality has been documented in the README if applicable.
  - [ ] New functionality has been thoroughly documented in the examples (please include helpful comments).
- [x] Changes are documented in the CHANGELOG.

### CODE REVIEW

File: lib/oneview-sdk/resource.rb [hunk 1]
```diff
@@ -361,6 +361,12 @@ def recursive_like?(other, data = @data)
         return false unless data && data.respond_to?(:[])
         if val.is_a?(Hash)
           return false unless data.class == Hash && recursive_like?(val, data[key.to_s])
+        elsif val.is_a?(Array) && val.first.is_a?(Hash)
```
Comment (jsmartt) [inline lib/oneview-sdk/resource.rb]: @ricardogpsf is this going to be good for **all** resources and data sets? I imagined just adding a constant to certain Resource classes with the key names that we should ignore the order of array elements. I wonder if this may have farther reaching negative effects where the array ordering is important.

File: CHANGELOG.md [hunk 2]
```diff
@@ -11,6 +11,7 @@
 - [#202](https://github.com/HewlettPackard/oneview-sdk-ruby/issues/202) The method #get_default_settings in LogicalInterconnectGroup is used on integration test
 - [#125](https://github.com/HewlettPackard/oneview-sdk-ruby/issues/125) References to resources C7000 in Synergy integration tests
 - [#212](https://github.com/HewlettPackard/oneview-sdk-ruby/issues/212) Unable to create a Server Profile with Deployment Plan settings
+- [#89](https://github.com/HewlettPackard/oneview-sdk-ruby/issues/89) Fix like? method for Logical Interconnect Groups
```
Comment (jsmartt) [inline CHANGELOG.md]: Also, I know it didn't come from this PR, but why are we suggesting the next version be 5.0.0? I don't see any breaking changes in the changelog.

Including @aalexmonteiro

File: lib/oneview-sdk/resource/api200/logical_interconnect_group.rb [hunk 3]
```diff
@@ -53,14 +47,25 @@ def self.get_default_settings(client)
       # @param [String] type Interconnect type
       # @raise [StandardError] if a invalid type is given then raises an error
       def add_interconnect(bay, type)
+        interconnect_type = OneviewSDK::Interconnect.get_type(@client, type)
+        raise OneviewSDK::NotFound unless interconnect_type
```
Comment (jsmartt) [inline lib/oneview-sdk/resource/api200/logical_interconnect_group.rb]: Provide a message for the user saying the resource type and name that wasn't found

File: lib/oneview-sdk/resource/api200/logical_interconnect_group.rb [hunk 4]
```diff
@@ -79,37 +84,52 @@ def get_settings
...
+        ensure_client && ensure_uri
+        verify_interconnects_before_save!
         update_options = {
           'If-Match' =>  @data.delete('eTag'),
           'Body' => @data
         }
         response = @client.rest_put(@data['uri'], update_options, @api_version)
         body = @client.response_handler(response)
         set_all(body)
+        self
```
Comment (jsmartt) [inline lib/oneview-sdk/resource/api200/logical_interconnect_group.rb]: Unnecessary `self`. `#set_all` returns self

File: lib/oneview-sdk/resource.rb (hunk 1 above)
Comment (ricardogpsf) [inline lib/oneview-sdk/resource.rb]: With this code, the problem with ordered array just will occur when the arrays are of objects, if this is a problem for us, I can change the code =). When the array is of strings or numbers for example, the order is considered because the comparison occurs with `array == other_array`.
I like this idea of specifying the attibutes that are arrays ordered or not, because even when the array is of strings I can need compare without a specific order.

File: lib/oneview-sdk/resource/api200/logical_interconnect_group.rb (hunk 3 above)
Comment (ricardogpsf) [inline lib/oneview-sdk/resource/api200/logical_interconnect_group.rb]: But the error is catched in this method yet. It is not throwed to user.

Comment (jsmartt) [inline lib/oneview-sdk/resource/api200/logical_interconnect_group.rb]: Ah! Nevermine. Thanks 😀

File: lib/oneview-sdk/resource.rb (hunk 1 above)
Comment (jsmartt) [inline lib/oneview-sdk/resource.rb]: I'm OK with this change as long as we can verify that it won't negatively impact other resources, but the only way I can think of verifying that is by looking through every single resource's API docs. I think I'd rather update this code than do that. lol

Comment (ricardogpsf) [inline lib/oneview-sdk/resource.rb]: @aalexmonteiro  @tmiotto @fgbulsoni What you think about this code?

File: CHANGELOG.md (hunk 2 above)
Comment (aalexmonteiro) [inline CHANGELOG.md]: @jsmartt , because we will start api500 development soon. After these PRs are merged into the master, I will open a PR of that code in the private github to develop the API500. Let me know your thoughts on this.

Comment (ricardogpsf) [inline CHANGELOG.md]: I imagine that ` ## Suggested release: v5.0.0` is really just a suggestion, right?!
Next release, for now, should not be 5.0.

File: lib/oneview-sdk/resource.rb (hunk 1 above)
Comment (aalexmonteiro) [inline lib/oneview-sdk/resource.rb]: I agree with @jsmartt . Just check the impact on other features but I think this will work fine.

Comment (tmiotto) [inline lib/oneview-sdk/resource.rb]: Array of Hashes in OneView does not require any specific order, actually, if you look close into the hashes in these types of arrays, each has an index or sort of defined inside. (e.g. Server Profile connections have connectionID that is a index, or in Logical Interconnect Groups  interconnectMapTemplates that each specify bay and enclosure index)

File: lib/oneview-sdk/resource/api200/logical_interconnect_group.rb [hunk 5]
```diff
@@ -53,14 +47,25 @@ def self.get_default_settings(client)
...
-      rescue StandardError
+
+        unless entry_already_present
+          new_entry = new_interconnect_entry_template(bay, interconnect_type['uri'])
+          @data['interconnectMapTemplate']['interconnectMapEntryTemplates'] << new_entry
+        end
+
+      rescue OneviewSDK::NotFound
         list = OneviewSDK::Interconnect.get_types(@client).map { |t| t['name'] }
         raise "Interconnect type #{type} not found! Supported types: #{list}"
```
Comment (tmiotto) [inline lib/oneview-sdk/resource/api200/logical_interconnect_group.rb]: I'm wondering why raising and rescuing a NotFound error, to then raise a StandardError

File: lib/oneview-sdk/resource/api200/logical_interconnect_group.rb [hunk 6]
```diff
@@ -53,14 +47,25 @@ def self.get_default_settings(client)
       # @param [String] type Interconnect type
       # @raise [StandardError] if a invalid type is given then raises an error
```
Comment (tmiotto) [inline lib/oneview-sdk/resource/api200/logical_interconnect_group.rb]: @ raise [StandardError] if ~a~ an invalid type is given ~then raises an error~
Remember YARD will parse it to something like: **raises StandardError if an invalid type is given**

File: spec/unit/resource/api300/c7000/logical_interconnect_group_spec.rb [hunk 7]
```diff
@@ -30,13 +29,13 @@
       expect(OneviewSDK::Interconnect).to receive(:get_type).with(@client_300, @type)
         .and_return('uri' => '/rest/fake')
       @item.add_interconnect(3, @type)
-      expect(@item['interconnectMapTemplate']['interconnectMapEntryTemplates'][2]['permittedInterconnectTypeUri'])
+      expect(@item['interconnectMapTemplate']['interconnectMapEntryTemplates'].first['permittedInterconnectTypeUri'])
```
Comment (tmiotto) [inline spec/unit/resource/api300/c7000/logical_interconnect_group_spec.rb]: expect also it to in bay 3

File: spec/unit/resource_spec.rb [hunk 8]
```diff
@@ -170,10 +170,81 @@
       expect(res.like?(data: { key2: 'val2' })).to eq(false)
     end
 
-    it 'requires the other objet to respond to .each' do
+    it 'requires the other object to respond to .each' do
       res = OneviewSDK::Resource.new(@client_200)
       expect { res.like?(nil) }.to raise_error(/Can't compare with object type: NilClass/)
     end
+
+    context 'when compare similar objects into array' do
```
Comment (tmiotto) [inline spec/unit/resource_spec.rb]: when ~compare~ comparing similar objects ~into array~ inside arrays

File: spec/unit/resource_spec.rb [hunk 9]
```diff
@@ -170,10 +170,81 @@
...
+        expect(res.like?(uri: '/rest/fake', list: [])).to eq(false)
+      end
+
+      it 'should return false if current array is empty' do
+        options = { uri: '/rest/fake', list: [] }
+        res = OneviewSDK::Resource.new(@client_200, options)
+        expect(res.like?(uri: '/rest/fake', list: [{ uri: '/rest/child/1' }])).to eq(false)
+      end
+
+      it 'should return false if current value is null' do
```
Comment (tmiotto) [inline spec/unit/resource_spec.rb]: it 'should return false if current value is ~null~ nil'

File: spec/unit/resource_spec.rb [hunk 10]
```diff
@@ -170,10 +170,81 @@
...
+        expect(res.like?(uri: '/rest/fake', list: [{ uri: '/rest/child/1' }])).to eq(true)
+      end
+
+      it 'should return true if array is empty' do
+        options = { uri: '/rest/fake', list: [] }
+        res = OneviewSDK::Resource.new(@client_200, options)
+        expect(res.like?(uri: '/rest/fake', list: [])).to eq(true)
+      end
+
+      it 'should return true if value is null' do
```
Comment (tmiotto) [inline spec/unit/resource_spec.rb]: it 'should return true if value is ~null~ nil'

File: spec/unit/resource_spec.rb (hunk 9 above)
Comment (tmiotto) [inline spec/unit/resource_spec.rb]: What's the difference  between `it 'should return true if value is nil'` and `it 'should return false if current value is nil'`? Looking at the test I can see the difference, but the title should describe clearly what is the intention, and just reading the title I can't tell what exactly is the difference, making them look paradoxical.

File: CHANGELOG.md (hunk 2 above)
Comment (tmiotto) [inline CHANGELOG.md]: I **strongly** recommend changing the suggested release to v4.1.1

File: lib/oneview-sdk/resource/api200/logical_interconnect_group.rb (hunk 5 above)
Comment (ricardogpsf) [inline lib/oneview-sdk/resource/api200/logical_interconnect_group.rb]: I kept the message that is shown to user: "Interconnect type #{type} not found! Supported types: #{list}" if a invalid type is given. The rescue of NotFound worked as a flux breaking, the error is treated at end of the method.

Comment (tmiotto) [inline lib/oneview-sdk/resource/api200/logical_interconnect_group.rb]: But it is still a NotFound error...

File: spec/unit/resource_spec.rb (hunk 9 above)
Comment (ricardogpsf) [inline spec/unit/resource_spec.rb]: I will change the title to "should return false if the value of array inside Resource that called the method is nil". 
What do you think?

File: lib/oneview-sdk/resource/api200/logical_interconnect_group.rb (hunk 6 above)
Comment (ricardogpsf) [inline lib/oneview-sdk/resource/api200/logical_interconnect_group.rb]: Thanks!

File: lib/oneview-sdk/resource/api200/logical_interconnect_group.rb (hunk 5 above)
Comment (ricardogpsf) [inline lib/oneview-sdk/resource/api200/logical_interconnect_group.rb]: ah, ok. I understood now. :D
