### PR TITLE
Golden Image i3s API300 Support

### LINKED ISSUE #118: I3S - Golden Image API 300 Support
### Scenario/Intent
Use the Image Streamer - Golden Image resource for API 300 C7000/Synergy.

### Environment Details
 - **OneView SDK Version: Future
 - **OneView Appliance Version: 300
 - **OneView Client API Version: 300
 - **Ruby Version: 2.2.3+
 - **Platform: w/e

### Steps to Reproduce
Trying to run the resource of Image Streamer for API 300.

### Expected Result
Being able to call the resource methods and use it.

### Actual Result
It's currently not implemented.

### PR DESCRIPTION
**Pull request by aalexmonteiro**
### Description
Implementation of the golden image for i3s API300 support.

### Issues Resolved
Fixes #118 

### Check List
- [x] New functionality includes testing.
  - [x] All tests pass (`$ rake test`).
- [ ] New functionality has been documented in the README if applicable.
  - [x] New functionality has been thoroughly documented in the examples (please include helpful comments).
- [x] Changes are documented in the CHANGELOG.

### CODE REVIEW

**Comment by aalexmonteiro** [comment]
This PR depends of the PRs #157 and #158.

File: lib/oneview-sdk/image-streamer/resource/api300/golden_image.rb [hunk 1]
```diff
@@ -10,13 +10,123 @@
...
+        def initialize(client, params = {}, api_ver = nil)
+          super
+          # Default values:
+          @data['type'] ||= 'GoldenImage'
+        end
+
+        # Download the details of the golden image capture logs which has been archived based on the specific attribute ID.
+        # @param [String] file_path
+        # @return [True] When was saved successfully
+        def get_details_archive(file_path)
```
Comment (jsmartt) [inline lib/oneview-sdk/image-streamer/resource/api300/golden_image.rb]: Minor thing here, but I'd probably recommend it being named `download_details_archive`. Either way is OK, but perhaps this way it's more clear that it's saving it to a file?

File: lib/oneview-sdk/image-streamer/resource/api300/golden_image.rb [hunk 2]
```diff
@@ -10,13 +10,123 @@
...
+        # @param [OneviewSDK::ImageStreamer::API300::OsVolumes] os_volume
+        def set_os_volume(os_volume)
+          raise IncompleteResource, 'Please set the OS Volume\'s uri attribute!' unless os_volume['uri']
+          set('osVolumeURI', os_volume['uri'])
+        end
+
+        # Sets the build plan
+        # @param [OneviewSDK::ImageStreamer::API300::BuildPlan] build_plan
+        def set_build_plan(build_plan)
+          raise IncompleteResource, 'Please set the Build Plan\'s uri attribute!' unless build_plan['uri']
```
Comment (jsmartt) [inline lib/oneview-sdk/image-streamer/resource/api300/golden_image.rb]: In both of these set methods, it probably wouldn't hurt trying a retrieve before raising the uri not set error, similar to [here](https://github.com/HewlettPackard/oneview-sdk-ruby/blob/master/lib/oneview-sdk/resource/api200/enclosure_group.rb#L55). It would be good to have some consistency between resources

File: lib/oneview-sdk/image-streamer/resource/api300/golden_image.rb [hunk 3]
```diff
@@ -10,13 +10,123 @@
...
+          options['Content-Type'] = 'application/json'
+          options['X-Api-Version'] = @client.api_version.to_s
+          options['auth'] = @client.token
+          options.each do |key, val|
+            req[key] = val
+          end
+
+          http_request = Net::HTTP.new(uri.host, uri.port)
+          http_request.use_ssl = true
+          http_request.verify_mode = OpenSSL::SSL::VERIFY_NONE
```
Comment (jsmartt) [inline lib/oneview-sdk/image-streamer/resource/api300/golden_image.rb]: Also, just curious, will this ever be a long enough request that we'll want to set the read_timeout like we do below?

File: lib/oneview-sdk/image-streamer/resource/api300/golden_image.rb [hunk 4]
```diff
@@ -10,13 +10,128 @@
...
+          @data['type'] ||= 'GoldenImage'
+        end
+
+        # Download the details of the golden image capture logs which has been archived based on the specific attribute ID.
+        # @param [String] file_path
+        # @return [True] When was saved successfully
+        def download_details_archive(file_path)
+          ensure_client && ensure_uri
+          resp = @client.rest_api(:get, "#{BASE_URI}/archive/#{@data['uri'].split('/').last}")
+          File.open(file_path, 'wb') { |file| file.write(resp.body) }
```
Comment (jsmartt) [inline lib/oneview-sdk/image-streamer/resource/api300/golden_image.rb]: @aalexmonteiro , I pushed up a commit with a few changes, mainly of documentation, but there are some other things in there too:
- Replicate the client's rest_api method in terms of ssl and cert_store options.
- I also made the data_options param required, since the default still raises an error saying it needs a name and description. Let me know if you think this is a good change.

Also, I had a question about this method. We're not running the response through the response_handler, so if this request fails, the output of that file will be the error text, but it doesn't look like this method will raise any sort of error or warning. I think this needs some sort of error handling, but will leave it up to your discretion on how to do so.

Comment (aalexmonteiro) [inline lib/oneview-sdk/image-streamer/resource/api300/golden_image.rb]: @jsmartt , I liked the changes. I'll make the change suggested by you. Thanks!

Comment (aalexmonteiro) [inline lib/oneview-sdk/image-streamer/resource/api300/golden_image.rb]: @jsmartt , Jared, I made the change but I can only certify that it is correct when I test in real hardware. Let me know what you think of this solution?

Comment (jsmartt) [inline lib/oneview-sdk/image-streamer/resource/api300/golden_image.rb]: I think it looks pretty good :)

File: examples/image-streamer/api300/golden_image.rb [hunk 5]
```diff
@@ -0,0 +1,88 @@
...
+require_relative '../../_client_i3s' # Gives access to @client
+
+# Example: Create a golden image for an API300 Image Streamer
+# NOTE: This will create a golden images named like 'Golden_Image_1' and 'Golden_Image_2', then delete it.
+# NOTE: You'll need to add the following instance variables to the _client_i3s.rb file with valid URIs for your environment:
+#   @golden_image_download_path
+#   @golden_image_upload_path
+#   @golden_image_log_path
+
+os_volumes = OneviewSDK::ImageStreamer::API300::OsVolumes.find_by(@client, {}).first
```
Comment (ricardogpsf) [inline examples/image-streamer/api300/golden_image.rb]: **OsVolume** instead of OsVolumes

File: spec/integration/image-streamer/api300/golden_image/create_spec.rb [hunk 6]
```diff
@@ -0,0 +1,81 @@
...
+RSpec.describe klass, integration_i3s: true, type: CREATE, sequence: i3s_seq(klass) do
+  include_context 'integration i3s api300 context'
+
+  let(:golden_image_upload_path) { 'spec/support/vmwareesxi6_test.zip' }
+  let(:golden_image_download_path) { 'spec/support/golden_image_test.zip' }
+  let(:golden_image_log_path) { 'spec/support/details_gi.log' }
+
+  describe '#create' do
+    it 'creates a golden image' do
+      os_volumes = OneviewSDK::ImageStreamer::API300::OsVolumes.find_by($client_i3s_300, {}).first
```
Comment (ricardogpsf) [inline spec/integration/image-streamer/api300/golden_image/create_spec.rb]: OsVolume (singular)

File: examples/image-streamer/api300/golden_image.rb (hunk 5 above)
Comment (aalexmonteiro) [inline examples/image-streamer/api300/golden_image.rb]: I'm waiting for the PR #157 to be approved.

File: spec/integration/image-streamer/api300/golden_image/create_spec.rb (hunk 6 above)
Comment (aalexmonteiro) [inline spec/integration/image-streamer/api300/golden_image/create_spec.rb]: I'm waiting for the PR #157 to be approved.

File: Rakefile [hunk 7]
```diff
@@ -252,6 +252,5 @@ end
 desc 'Run rubocop & integration tests for Image Streamer & specified path'
 task 'test:i3s:path', [:path] do |_t, spec|
   spec_pattern = spec['path']
-  Rake::Task[:rubocop].invoke
```
Comment (tmiotto) [inline Rakefile]: Why did you remove rubocop?

Also, if it was really intended to be removed, you forgot to change the description of the task.

File: examples/image-streamer/api300/golden_image.rb [hunk 8]
```diff
@@ -0,0 +1,88 @@
...
+#
+# Unless required by applicable law or agreed to in writing, software distributed
+# under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
+# CONDITIONS OF ANY KIND, either express or implied. See the License for the
+# specific language governing permissions and limitations under the License.
+
+require_relative '../../_client_i3s' # Gives access to @client
+
+# Example: Create a golden image for an API300 Image Streamer
+# NOTE: This will create a golden images named like 'Golden_Image_1' and 'Golden_Image_2', then delete it.
```
Comment (tmiotto) [inline examples/image-streamer/api300/golden_image.rb]: **This will create** ~~a~~ **golden images named** ~~like~~ **'Golden_Image_1' and 'Golden_Image_2'** ~~then delete it~~ **and then, it will delete them**.

File: lib/oneview-sdk/image-streamer/resource/api300/golden_image.rb [hunk 9]
```diff
@@ -10,13 +10,133 @@
...
+
+        # Upload a golden image from the specified local file path.
+        # Only the .zip format file can be used for upload.
+        # @param [OneviewSDK::ImageStreamer::Client] client The client object for the Image Streamer appliance
+        # @param [String] file_path
+        # @param [Hash] data_options Attributes of the golden image, passed in the request
+        # @option data_options [String] :name The name of the Golden Image (required)
+        # @option data_options [String] :description The description of the Golden Image (required)
+        # @param [Integer] timeout The number of seconds to wait for the request to complete
+        # @return [Hash] hash with a String
```
Comment (tmiotto) [inline lib/oneview-sdk/image-streamer/resource/api300/golden_image.rb]: But what is this hash and what is the string?

**Comment by tmiotto** [comment]
Also, there are a lot of HTTP requests being done here, it would make sense to move them to the `client.rb` or `rest.rb` files?

File: Rakefile (hunk 7 above)
Comment (ricardogpsf) [inline Rakefile]: The task invoked with the command `Rake::Task['spec:integration:i3s'].invoke` already executes the rubocop task.

Comment (aalexmonteiro) [inline Rakefile]: This line is called `Rake::Task['spec:integration:i3s'].invoke` and in the task the command `Rake::Task[:rubocop].invoke` is called.

**Comment by aalexmonteiro** [comment]
@tmiotto , the @ricardogpsf who is implementing the **Artifacts Bundle**, implemented this in a separate file. I can then change when your appeal is approved. What do you think?

**Comment by tmiotto** [comment]
Sorry @aalexmonteiro , you're saying he implemented the rest calls in a separate file? If so it is already merged?

**Comment by aalexmonteiro** [comment]
@tmiotto , yes! He created something similar to file_upload_helper. This has not yet been merged. If this is approved, I can make the changes.
